### ISSUE TITLE
how to add a fadeIn effect as images load inside loaded window?

### ISSUE THREAD

**Issue by inglesuniversal** [ApoorvSaxena/lozad.js#188]
Hello:

Great script!

I would like to know if there is a way to add a fadeIn effect as images are loaded on the current screen, to avoid the empty box fill in effect which looks kinda old school websites.

Best regards

**Comment by ALPIXELMaiki** [comment]
Hi !
You can do it with CSS, by binding the "data-loaded" attribute.

Here my code, it works like a charm :
`/* *****
    @name: showLazyImg
    @description: Animate img and backstretch when elements are loaded with lozad
***** */
img[data-loaded="true"],
[data-loaded="true"] img {
  animation-name: showLazyImg;
  animation-duration: 0.7s;
  animation-fill-mode: both;
}
@keyframes showLazyImg {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}`

**Comment by Cedric-ruiu** [comment]
`data-loaded` wouldn't mean that your images are fully loaded, so your animation start before & potentially end before the images fully loaded. To enhance this behavior I extend JS & add another attribut `data-fully-loaded`.

```javascript
const images = document.getElementsByClassName('lozad');
for (const image of images) {
  if (!image.getAttribute('data-background-image')) {
    image.onload = function() {
      this.setAttribute('data-fully-loaded', true);
    };
  }
}
```

Just rename attribut from @ALPIXELMaiki 

``` css
img[data-fully-loaded="true"], [data-fully-loaded="true"] img { animation-name: showLazyImg; animation-duration: 0.7s; animation-fill-mode: both; } @keyframes showLazyImg { from { opacity: 0; } to { opacity: 1; } }
```

This tricks works properly but only for `<img>` present on the initial load. It need another treatment to add this behavior on the `<img>` inserted after initial loading (I don't write it, too much extra code).

And this tricks works only on `<img>` but not with `data-background-image`, impossible I think to do it without extending lozad.

The better way : fire events in lozad when a ressource is fully loaded. And fire event too when a ressource start to load (equivalent to `data-loaded`), it can be useful.

**Comment by Cedric-ruiu** [comment]
Just an update for CSS fadeIn. Add a class `.no-fade` to disable fade on `<img>` inserted after initial load. This update prevent blinking when images appear. And it works well with `iframes`.

```scss
.lozad[data-src] {
  &:not(.no-fade) {
    transition: opacity 0.8s ease;
    opacity: 0;

    &[data-fully-loaded="true"] {
      opacity: 1;
    }
  }
}
```
